### ISSUE TITLE
Add DNS to the gcloud-java test apps

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java-examples#5]
These apps are useful for testing gcloud-java on the platforms we support.  We should add more tests as new client libraries become available, like DNS.

@mderka, if/when you have time, do you mind adding a bit of really simple DNS code to these apps?

**Comment by mderka** [comment]
I will have a look at it when I am completely done with the batch implementation.

**Comment by tswast** [comment]
[google-cloud-dns samples](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-examples/src/main/java/com/google/cloud/examples/dns) are in the google-cloud-java repo.
